name: Deploy Next.js Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy automático no primeiro commit
  # Descomente as linhas abaixo se quiser deploy automático em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Create production environment file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=https://expandev-app-03.azurewebsites.net" > .env.production
          cat .env.production

      - name: Update next.config.mjs with backend URL
        working-directory: ./frontend
        run: |
          cat > next.config.mjs << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'standalone',
            async rewrites() {
              return [
                {
                  source: '/api/:path*',
                  destination: 'https://expandev-app-03.azurewebsites.net/api/:path*',
                },
              ];
            },
          };

          export default nextConfig;
          EOF

      - name: npm install and build
        working-directory: ./frontend
        run: |
          npm install
          NEXT_PUBLIC_API_URL=https://expandev-app-03.azurewebsites.net npm run build

          # Verificar se standalone foi criado
          if [ -d ".next/standalone" ]; then
            echo "Standalone build detected"
            # Copiar arquivos estáticos necessários
            if [ -d "./public" ]; then
              cp -R ./public ./.next/standalone/public
            fi
            cp -R ./.next/static ./.next/standalone/.next/static
          else
            echo "Standard Next.js build (no standalone)"
          fi

      - name: Zip artifact for deployment
        working-directory: ./frontend
        run: |
          if [ -d ".next/standalone" ]; then
            cd .next/standalone
            zip -r ../../release.zip .
            cd ../..
          else
            # Para builds padrão do Next.js, zipar toda a pasta .next
            zip -r release.zip .next public package.json package-lock.json node_modules
          fi
          echo "Release zip created"
          ls -lh release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: ./frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Wait for Azure to be ready
        run: sleep 30

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-app-04'
          package: .
          startup-command: 'node server.js'
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: false
          WEBSITE_RUN_FROM_PACKAGE: 0
          ENABLE_ORYX_BUILD: false